# Generated by Django 2.2.4 on 2019-08-15 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_pay_ratings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='user_work_ratings',
            field=models.IntegerField(default=0),
        ),
    ]
